### ISSUE TITLE
When initialize ons-modal angularjs

### ISSUE THREAD

**Issue by J261** [OnsenUI/OnsenUI#1604]
angular.min.js:118TypeError: Cannot read property 'setAnimationOptions' of undefined
    at Class.init (http://localhost/?/app/onsen/js/angular-onsenui.min.js:2:19054)
    at new Class (http://localhost/?/app/onsen/js/angular-onsenui.min.js:2:191)
    at Object.pre (http://localhost/?/app/onsen/js/angular-onsenui.min.js:6:11662)
    at http://localhost/?/app/onsen/js/angular.min.js:16:71
    at la (http://localhost/?/app/onsen/js/angular.min.js:81:90)
    at p (http://localhost/?/app/onsen/js/angular.min.js:66:149)
    at g (http://localhost/?/app/onsen/js/angular.min.js:58:481)
    at p (http://localhost/?/app/onsen/js/angular.min.js:66:281)
    at g (http://localhost/?/app/onsen/js/angular.min.js:58:481)
    at g (http://localhost/?/app/onsen/js/angular.min.js:58:498)
<ons-modal id="modal_wait" class="modal" style="display: none; z-index: 10001;">

**Comment by argelius** [comment]
@J261 Can you provide information how  to reproduce this?

**Comment by J261** [comment]
just putting `<ons-modal id="modal_wait"></ons-progress-circular></ons-modal>` on body

**Comment by J261** [comment]
using AngularJS v1.5.8

**Comment by J261** [comment]
the error occurs when and onsen.js files in the head of the document. if you put it on the body bottom the error not occur.

**Comment by argelius** [comment]
Closing this now. Not enough information to proceed.

Please feel to open it again if you can provide steps to reproduce.
