### ISSUE TITLE
Unhandled Promise Rejection on pagePush.

### ISSUE THREAD

**Issue by Rall3n** [OnsenUI/OnsenUI#1747]
__Environment__ 

```
[Core]
    Onsen UI 2.0.4

[Framework]
    None

[Framework binding]
    None

[Additional libraries]
    jQuery 3.1.1

[Platform]
    Mobile - Android 4.4.2

[Browser]
    Desktop - Chrome 55.0.2883.75
```

__Encountered problem__

As soon as I want to push this certain 'page2.html' onto the page stack, I get an ***Possible Unhandled Promise Rejection: [object DOMException]*** error, and after that I always get an ***Possible Unhandled Promise Rejection: pushPage is already running.*** Only happens with this page/code.

Code I use to push this certain page:
```
document.querySelector('#myNavigator').pushPage('pages/page2.html', { data: $(this).data('event') });
```

Stack looks like this:
```
splash.html
login.html
page1.html
```

**Full [object DOMException]**
```
Possible Unhandled Promise Rejection: [object DOMException]
onsenui.js (3851,15)
   "Possible Unhandled Promise Rejection:"
   {
      __proto__: { },
      code: 5,
      message: The string contains invalid characters.,
      name: InvalidCharacterError,
      stack: Error: The string contains invalid characters.
    at initialize (file:///android_asset/www/lib/onsenv2.0.4/js/onsenui.js:3553:12)
    at innerHTML.innerHTML (file:///android_asset/www/lib/onsenv2.0.4/js/onsenui.js:3575:30)
    at Object.util.createElement (file:///android_asset/www/lib/onsenv2.0.4/js/onsenui.js:4675:6)
    at file:///android_asset/www/lib/onsenv2.0.4/js/onsenui.js:9747:27
    at file:///android_asset/www/lib/onsenv2.0.4/js/onsenui.js:3690:15
   }

```

**Comment by Rall3n** [comment]
Fixed it! Was a random semicolon that had been hidden in my code.
