### ISSUE TITLE
Vue | Pull-hook issue: `Cannot read property 'style' of undefined` on `ons-pull-hook#disconnectedCallback`

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#1925]
__Environment__

  
```
[Core]
  onsenui 2.2.3
  
[Framework]
  vue 2.2.4

[Framework binding]
 vue-onsenui latest

[Platform]
  Desktop - OS X 10.12.0 64-bit

[Browser]
  Desktop - Chrome 56.0.2924.87 on OS X 10.12.0 64-bit
```

__Encountered problem__

The official example in tutorial.onsen.io causes the following error.

```
Uncaught TypeError: Cannot read property 'style' of undefined
    at HTMLElement.disconnectedCallback (https://unpkg.com/onsenui@2.2.3/js/onsenui.js:21103:24)
    at r.disconnectedCallback (https://unpkg.com/onsenui@2.2.3/js/onsenui.js:2323:80)
    at z (https://unpkg.com/onsenui@2.2.3/js/onsenui.js:2286:44)
    at HTMLDivElement.appendChild (https://unpkg.com/onsenui@2.2.3/js/onsenui.js:2472:42)
    at https://unpkg.com/onsenui@2.2.3/js/onsenui.js:19142:21
    at Array.forEach (native)
    at HTMLElement._compile (https://unpkg.com/onsenui@2.2.3/js/onsenui.js:19140:41)
    at https://unpkg.com/onsenui@2.2.3/js/onsenui.js:18925:16
    at https://unpkg.com/onsenui@2.2.3/js/onsenui.js:8220:12
    at Array.forEach (native)
```

Maybe the current `ons-pull-hook#disconnectedCallback` is not compatible with the new CE polyfill added since `onsenui@2.2.3`.

__How to reproduce__
  

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<template id="main">
  <v-ons-page>
    <v-ons-toolbar>
      <div class="center">Pull Hook</div>
    </v-ons-toolbar>

    <v-ons-pull-hook
      :action="loadItem"
      @changestate="state = $event.state"
    >
      <span v-show="state === 'initial'"> Pull to refresh </span>
      <span v-show="state === 'preaction'"> Release </span>
      <span v-show="state === 'action'"> Loading... </span>
    </v-ons-pull-hook>

    <v-ons-list>
      <v-ons-list-item v-for="item in items">
        {{item}}
      </v-ons-list-item>
    </v-ons-list>
  </v-ons-page>
</template>

<div id="app"></div>
```

- __JS__

```javascript
new Vue({
  el: '#app',
  template: '#main',
  data() {
    return {
      state: 'initial',
      items: [1, 2, 3]
    };
  },
  methods: {
    loadItem(done) {
      setTimeout(() => {
        this.items = [...this.items, this.items.length + 1];
        done();
      }, 400);
    }
  }
});
```

**Comment by asial-matagawa** [comment]
Carousel, Form Input, Popover, Pull Hook, Select, Range, ... are also broken.

**Comment by asial-matagawa** [comment]
I have identified the reason why 2.2.3 broke vue-onsenui.
This code works differently on the Chrome CE1 Impl and the new CE1 polyfill:
```js
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" href="">
  <script>
    if (window.customElements) { // even if native CE1 impl exists, use polyfill
        window.customElements.forcePolyfill = true;
    }
  </script>
  <script src="vendor/custom-elements-1.0.0-rc.2/custom-elements.min.js"></script>
  <script>
    customElements.define('x-foo', class extends HTMLElement {
      constructor() {
        super();
        console.log(this.tagName + '#constructor');
      }

      connectedCallback() { console.log(this.tagName + '#connectedCallback');
        // Move the child element to outside of `document`
        document.createElement('div').appendChild(this.firstChild);
      }

      disconnectedCallback() { console.log(this.tagName + '#disconnectedCallback');
      }
    });

    customElements.define('x-bar', class extends HTMLElement {
      constructor() {
        super();
        console.log(this.tagName + '#constructor');
      }

      connectedCallback() { console.log(this.tagName + '#connectedCallback');
      }

      disconnectedCallback() { console.log(this.tagName + '#disconnectedCallback');
      }
    });
  </script>
</head>
<body>
  <script>
    const foo = document.createElement('x-foo');
    {
      const bar = document.createElement('x-bar');
      foo.appendChild(bar);
    }

    document.body.appendChild(foo);
  </script>
</body>
</html>
```

----

Expected (Chrome CE1 Impl):

```
X-FOO#constructor
X-BAR#constructor
X-FOO#connectedCallback
X-BAR#connectedCallback
X-BAR#disconnectedCallback
```

----

Result (the new CE1 polyfill):

```
X-FOO#constructor
X-BAR#constructor
X-FOO#connectedCallback
X-BAR#disconnectedCallback
X-BAR#connectedCallback
```

**Comment by asial-matagawa** [comment]
At least this issue has been fixed by https://github.com/OnsenUI/OnsenUI/pull/1932/commits/3cdc5ca3bf1d63d5e291b8b639c2ec442af9cc3d.

Closing this.
