### ISSUE TITLE
Adding animation prop to SplitterSide component throws an error.

### ISSUE THREAD

**Issue by airamrguez** [OnsenUI/OnsenUI#2026]
__Environment__ 

```
[Core]
    onsenui 2.3.1

[Framework]
    react 15.5

[Framework binding]
    react-onsenui 1.3.3

[Platform]
    all

[Browser]
    all
```

__Encountered problem__

Adding animation prop to `SplitterSide` component throws an error.
```
Uncaught TypeError: Invalid value used as weak map key
    at WeakMap.set (native)
    at addCallback (https://unpkg.com/onsenui@2.3.1/js/onsenui.js:672:14)
    at contentReady (https://unpkg.com/onsenui@2.3.1/js/onsenui.js:688:3)
    at OverlaySplitterAnimator.activate (https://unpkg.com/onsenui@2.3.1/js/onsenui.js:6258:34)
    at HTMLElement._updateAnimation (https://unpkg.com/onsenui@2.3.1/js/onsenui.js:23672:22)
    at HTMLElement._update (https://unpkg.com/onsenui@2.3.1/js/onsenui.js:23579:24)
    at HTMLElement.attributeChangedCallback (https://unpkg.com/onsenui@2.3.1/js/onsenui.js:23571:12)
    at CustomElementInternals.attributeChangedCallback (https://unpkg.com/onsenui@2.3.1/js/onsenui.js:2783:45)
    at HTMLElement.setAttribute (https://unpkg.com/onsenui@2.3.1/js/onsenui.js:33414:15)
    at Object.setValueForAttribute (https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.min.js:12:16319)
```
__How to reproduce__

https://codepen.io/airamrguez/pen/JNxPVj?&editors=101

Open the console to see the logs.

**Comment by asial-matagawa** [comment]
@airamrguez 
Thank you for reporting!
It seems that `SplitterAnimator#activate` is called before the `ons-splitter-side` is connected to the DOM tree due to `attributeChangedCallback`. As a result `sideElement` has `null` as its value.
https://github.com/OnsenUI/OnsenUI/blob/885c875d3fe9f08b933cad2bc05375367abe424a/core/src/elements/ons-splitter/animator.js#L39

**Comment by asialgearoid** [comment]
Thanks for bringing this to our attention @kurtishouser. It looks like the previous fix was lost during a recent refactor of the side splitter. The issue is actually in the core, not the React bindings. I will fix this for the next release.
