### ISSUE TITLE
Latest OnsenUI 2.3.x not installed

### ISSUE THREAD

**Issue by GROL** [OnsenUI/OnsenUI#2041]
Hi,

There is a setup issue of the version 2.3.x, but there are no any problems with the version 2.2.x
I see in log some problems with the custom-elements repository (line 82)
Any ideas what I can do?

The npm-debug.log contained:

```
...
69 silly cache add   hosted:
69 silly cache add    { type: 'github',
69 silly cache add      ssh: 'git@github.com:onsenui/custom-elements.git#1.0.0-rc.3+mod.20170410.1',
69 silly cache add      sshUrl: 'git+ssh://git@github.com/onsenui/custom-elements.git#1.0.0-rc.3+mod.20170410.1',
69 silly cache add      httpsUrl: 'git+https://github.com/onsenui/custom-elements.git#1.0.0-rc.3+mod.20170410.1',
69 silly cache add      gitUrl: 'git://github.com/onsenui/custom-elements.git#1.0.0-rc.3+mod.20170410.1',
69 silly cache add      shortcut: 'github:onsenui/custom-elements#1.0.0-rc.3+mod.20170410.1',
69 silly cache add      directUrl: 'https://raw.githubusercontent.com/onsenui/custom-elements/1.0.0-rc.3%2Bmod.20170410.1/package.json' } }
70 verbose addRemoteGit caching github:onsenui/custom-elements#1.0.0-rc.3+mod.20170410.1
71 verbose addRemoteGit onsenui/custom-elements#1.0.0-rc.3+mod.20170410.1 is a repository hosted by github
72 silly tryGitProto attempting to clone git://github.com/onsenui/custom-elements.git#1.0.0-rc.3+mod.20170410.1
73 silly tryClone cloning onsenui/custom-elements#1.0.0-rc.3+mod.20170410.1 via git://github.com/onsenui/custom-elements.git#1.0.0-rc.3+mod.20170410.1
74 verbose tryClone git-github-com-onsenui-custom-elements-git-1-0-0-rc-3-mod-20170410-1-bf0be608 not in flight; caching
75 verbose correctMkdir C:\Users\GOleg\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
76 verbose request uri https://registry.npmjs.org/core-js
77 verbose request no auth needed
78 info attempt registry request try #1 at 2:24:53 PM
79 verbose etag W/"5924427b-3892a"
80 verbose lastModified Tue, 23 May 2017 14:08:59 GMT
81 http request GET https://registry.npmjs.org/core-js
82 warn addRemoteGit Error: not found: git
82 warn addRemoteGit     at getNotFoundError (C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:13:12)
82 warn addRemoteGit     at F (C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:68:19)
82 warn addRemoteGit     at E (C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:80:29)
82 warn addRemoteGit     at C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:89:16
82 warn addRemoteGit     at C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
82 warn addRemoteGit     at C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
82 warn addRemoteGit     at C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
82 warn addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
82 warn addRemoteGit  onsenui/custom-elements#1.0.0-rc.3+mod.20170410.1 resetting remote C:\Users\GOleg\AppData\Roaming\npm-cache\_git-remotes\git-github-com-onsenui-custom-elements-git-1-0-0-rc-3-mod-20170410-1-bf0be608 because of error: { Error: not found: git
82 warn addRemoteGit     at getNotFoundError (C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:13:12)
82 warn addRemoteGit     at F (C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:68:19)
82 warn addRemoteGit     at E (C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:80:29)
82 warn addRemoteGit     at C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:89:16
82 warn addRemoteGit     at C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
82 warn addRemoteGit     at C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
82 warn addRemoteGit     at C:\Users\GOleg\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
82 warn addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
83 info resetRemote resetting C:\Users\GOleg\AppData\Roaming\npm-cache\_git-remotes\git-github-com-onsenui-custom-elements-git-1-0-0-rc-3-mod-20170410-1-bf0be608 for onsenui/custom-elements#1.0.0-rc.3+mod.20170410.1
84 silly gentlyRm C:\Users\GOleg\AppData\Roaming\npm-cache\_git-remotes\git-github-com-onsenui-custom-elements-git-1-0-0-rc-3-mod-20170410-1-bf0be608 is being purged
85 verbose gentlyRm don't care about contents; nuking C:\Users\GOleg\AppData\Roaming\npm-cache\_git-remotes\git-github-com-onsenui-custom-elements-git-1-0-0-rc-3-mod-20170410-1-bf0be608
```

**Comment by asial-matagawa** [comment]
Hi, @GROL!
This kind of error occurs when Git is not installed correctly on the `PATH` in your environment.
Could you install Git and try it again?

Closing this.
