### ISSUE TITLE
[react] babel-lint missing after yarn install

### ISSUE THREAD

**Issue by emj365** [OnsenUI/OnsenUI#2174]
with a fresh clone

```
→ yarn install
yarn install v0.24.6
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ npm run build

> react-onsenui@1.5.0 build /Users/michael/git/OnsenUI/bindings/react
> npm run lint && cross-env NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.config.js


> react-onsenui@1.5.0 lint /Users/michael/git/OnsenUI/bindings/react
> eslint --ext .js,.jsx src

Cannot find module 'babel-eslint'
Error: Cannot find module 'babel-eslint'
    at ModuleResolver.resolve (/Users/michael/git/OnsenUI/bindings/react/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at Object.load (/Users/michael/git/OnsenUI/bindings/react/node_modules/eslint/lib/config/config-file.js:554:42)
    at loadConfig (/Users/michael/git/OnsenUI/bindings/react/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/michael/git/OnsenUI/bindings/react/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/michael/git/OnsenUI/bindings/react/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/michael/git/OnsenUI/bindings/react/node_modules/eslint/lib/cli-engine.js:224:33)
    at processFile (/Users/michael/git/OnsenUI/bindings/react/node_modules/eslint/lib/cli-engine.js:303:18)
    at executeOnFile (/Users/michael/git/OnsenUI/bindings/react/node_modules/eslint/lib/cli-engine.js:672:25)
    at fileList.forEach.fileInfo (/Users/michael/git/OnsenUI/bindings/react/node_modules/eslint/lib/cli-engine.js:710:13)
    at Array.forEach (native)

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/michael/.nvm/versions/node/v6.10.3/bin/node" "/Users/michael/.nvm/versions/node/v6.10.3/bin/npm" "run" "lint"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-onsenui@1.5.0 lint: `eslint --ext .js,.jsx src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-onsenui@1.5.0 lint script 'eslint --ext .js,.jsx src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-onsenui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --ext .js,.jsx src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-onsenui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-onsenui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/michael/git/OnsenUI/bindings/react/npm-debug.log

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/michael/.nvm/versions/node/v6.10.3/bin/node" "/Users/michael/.nvm/versions/node/v6.10.3/bin/npm" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-onsenui@1.5.0 build: `npm run lint && cross-env NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-onsenui@1.5.0 build script 'npm run lint && cross-env NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-onsenui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && cross-env NODE_ENV=production webpack --progress --hide-modules --config webpack.prod.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-onsenui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-onsenui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/michael/git/OnsenUI/bindings/react/npm-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by emj365** [comment]
@frandiox could you give me some tips? please

**Comment by frandiox** [comment]
@emj365 Tips? About what? `yarn add babel-eslint -D` was enough to fix this.

**Comment by emj365** [comment]
@frandiox  would you like me to create PR with new `package.json` file?

**Comment by frandiox** [comment]
@emj365 No no, it's already fixed. Check the message from Github on top of these comments: `frandiox closed this in 026d125 19 minutes ago`. Commit here: 026d125

**Comment by asial-matagawa** [comment]
@emj365 
Hi, 
`react-onsenui` depends on the packages in `OnsenUI/node_modules` (includes `babel-eslint`) as well as those in `OnsenUI/bindings/react/node_modules/`, so actually this issue can be fixed if you run `yarn install` in the root directory of this repo (although @frandiox created a patch https://github.com/OnsenUI/OnsenUI/commit/026d1259d8e606e037758ae267f5d0580acc070e )

**Comment by emj365** [comment]
I got it. Thank you for fixing.

**Comment by frandiox** [comment]
@asial-matagawa Since `react-onsenui` has `eslint` as dev depency it should also have `babel-eslint` and don't rely on the parent directories :+1:

**Comment by asial-matagawa** [comment]
@frandiox 
Oh, I see. Thank you!
