### ISSUE TITLE
Unable to get property 'newAnimator' of undefined or null reference on IE

### ISSUE THREAD

**Issue by GinjiBan** [OnsenUI/OnsenUI#2182]
```
[Core]
    onsenui 2.5.4

[Framework]
    react 15.6.1

[Framework binding]
    react-onsenui 1.4.0

[Additional libraries]
    none

[Platform]
    Desktop - Windows 10

[Browser]
    Desktop - IE 11
```

__Encountered problem__
Getting the following error (IE only)

`Unhandled promise rejection TypeError: Unable to get property 'newAnimator' of undefined or null reference`

```
"TypeError: Unable to get property 'newAnimator' of undefined or null reference
   at _switchPage (http://localhost:8080/app.bundle.js:59372:7)
   at Anonymous function (http://localhost:8080/app.bundle.js:59493:11)
   at _loadPageElement (http://localhost:8080/app.bundle.js:58802:9)
   at Anonymous function (http://localhost:8080/app.bundle.js:59490:9)
   at Promise (http://localhost:8080/polyfill.bundle.js:6194:7)
   at setActiveTab (http://localhost:8080/app.bundle.js:59489:7)
   at Anonymous function (http://localhost:8080/app.bundle.js:45812:21)
   at Anonymous function (http://localhost:8080/app.bundle.js:214681:13)
   at Anonymous function (http://localhost:8080/app.bundle.js:214103:13)
   at Anonymous function (http://localhost:8080/app.bundle.js:213966:13)"
```

While putting console log on the onsenui.js file I noticed that

`_this._animatorFactory = new _animatorFactory2.default({...})` from TabbarElement was called before the `_switchPage` function on Chrome but **after** in IE

__How to reproduce__

Just switch page on the application.

**Comment by frandiox** [comment]
@GinjiBan Thanks for taking the time in debugging and reporting. As described in the readme and docs, we don't officially support IE nor test it. Also, I just changed `ons-tabbar` completely and doesn't even have animators anymore. The new version will be released probably tomorrow so I think there is no point in trying to fix this now :/

**Comment by GinjiBan** [comment]
@frandiox Thank you for the quick answer.

I guess I'll try again when the next version we'll be released and hope that it'll fix it ! :)
