### ISSUE TITLE
ons-search-input with ng-model

### ISSUE THREAD

**Issue by asalgueiro** [OnsenUI/OnsenUI#2192]
__Environment__ 

[Core]
    onsenui 2.6.0

[Framework]
    angular1 1.5.9

[Framework binding]
    angular-onsenui 2.1.0

[Additional libraries]
    none

[Platform]
    Desktop - Chrome

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__

When use <ons-search-input> with ng-model atribute Onsen throws an error:

"Error: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at https://unpkg.com/onsenui@2.6.0/js/onsenui.js:510:54
    at Array.forEach (<anonymous>)
    at Object.util.restoreClass (https://unpkg.com/onsenui@2.6.0/js/onsenui.js:509:29)
    at HTMLElement.attributeChangedCallback (https://unpkg.com/onsenui@2.6.0/js/onsenui.js:6445:26)
    at CustomElementInternals.attributeChangedCallback (https://unpkg.com/onsenui@2.6.0/js/onsenui.js:2877:45)
    at CustomElementInternals.upgradeElement (https://unpkg.com/onsenui@2.6.0/js/onsenui.js:2820:18)
    at CustomElementInternals.patchAndUpgradeTree (https://unpkg.com/onsenui@2.6.0/js/onsenui.js:2777:14)
    at HTMLElement.cloneNode (https://unpkg.com/onsenui@2.6.0/js/onsenui.js:35936:17)
    at Vb (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.min.js:31:364)
    at U.(anonymous function) [as clone] (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.min.js:197:332)"

__How to reproduce__

Simply add:  <ons-search-input ng-model="buscar" placeholder="Search"></ons-search-input>
to a page and the error occurs.

An example:
https://codepen.io/anon/pen/vexYrm?editors=1012

**Comment by frandiox** [comment]
This was fixed two days ago in d297dbf :+1:
