### ISSUE TITLE
Unable to install OnsenUI/react-onsenui dependencies

### ISSUE THREAD

**Issue by iliran11** [OnsenUI/OnsenUI#2295]
_Enviroment_

**OS:** Window 10
**Yarn:** 1.3.2
**Node:** 8.9.3 

I have cloned `OnsenUI/react-onsenui` repository in order to make a contribution.
When I am running `yarn install` i am getting the error log below: 

```
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ npm run build
[###################################################################################################------------------------------------------------------------------------------] 802/1429
> react-onsenui@1.0.3 build C:\projects\react-onsenui
> npm run lint && rollup -c


> react-onsenui@1.0.3 lint C:\projects\react-onsenui
> eslint --ext .js,.jsx src

resolve failed:  { Error: Cannot find module 'caniuse-db'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.requireRelative.resolve (C:\projects\react-onsenui\node_modules\require-relative\index.js:30:17)
    at resolve (C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:25:26)
    at findAndRemove (C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:67:11)
    at C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:111:13
    at Array.map (<anonymous>)
    at loadPreset (C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:103:29)
    at module.exports (C:\projects\react-onsenui\node_modules\modify-babel-preset\index.js:97:19)
    at Object.<anonymous> (C:\projects\react-onsenui\node_modules\babel-preset-es2015-rollup\index.js:3:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18) code: 'MODULE_NOT_FOUND' } caniuse-db
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.requireRelative.resolve (C:\projects\react-onsenui\node_modules\require-relative\index.js:30:17)
    at resolve (C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:25:26)
    at findAndRemove (C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:67:11)
    at C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:111:13
    at Array.map (<anonymous>)
    at loadPreset (C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:103:29)
    at module.exports (C:\projects\react-onsenui\node_modules\modify-babel-preset\index.js:97:19)
    at Object.<anonymous> (C:\projects\react-onsenui\node_modules\babel-preset-es2015-rollup\index.js:3:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18) code: 'MODULE_NOT_FOUND' } babel-runtime
resolve failed:  { Error: Cannot find module 'webpack-core'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.requireRelative.resolve (C:\projects\react-onsenui\node_modules\require-relative\index.js:30:17)
    at resolve (C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:25:26)
    at findAndRemove (C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:67:11)
    at C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:111:13
    at Array.map (<anonymous>)
    at loadPreset (C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:103:29)
    at module.exports (C:\projects\react-onsenui\node_modules\modify-babel-preset\index.js:97:19)
    at Object.<anonymous> (C:\projects\react-onsenui\node_modules\babel-preset-es2015-rollup\index.js:3:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18) code: 'MODULE_NOT_FOUND' } webpack-core
resolve failed:  { Error: Cannot find module '@onsenui'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.requireRelative.resolve (C:\projects\react-onsenui\node_modules\require-relative\index.js:30:17)
    at resolve (C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:25:26)
    at findAndRemove (C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:67:11)
    at C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:111:13
    at Array.map (<anonymous>)
    at loadPreset (C:\projects\react-onsenui\node_modules\modify-babel-preset\lib\serialize.js:103:29)
    at module.exports (C:\projects\react-onsenui\node_modules\modify-babel-preset\index.js:97:19)
    at Object.<anonymous> (C:\projects\react-onsenui\node_modules\babel-preset-es2015-rollup\index.js:3:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18) code: 'MODULE_NOT_FOUND' } @onsenui
Error transforming C:\projects\react-onsenui\src\index.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
Error: Error transforming C:\projects\react-onsenui\src\index.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (C:\projects\react-onsenui\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js:46:104)
    at Object.transform$1 [as transform] (C:\projects\react-onsenui\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js:117:18)
    at C:\projects\react-onsenui\node_modules\rollup\src\utils\transform.js:19:35
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-onsenui@1.0.3 build: `npm run lint && rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-onsenui@1.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\liran\AppData\Roaming\npm-cache\_logs\2017-12-29T16_14_23_770Z-debug.log
error Command failed with exit code 1.
```

**Comment by frandiox** [comment]
@iliran11 Hi! Not sure why that happened. Can you try `yarn install --pure-lockfile` in `onsenui`, `onsenui/css-components` and `onsenui/bindings/react`? :confused:

**Comment by asialgearoid** [comment]
Closing due to lack of a reply.
