### ISSUE TITLE
Theme customization build fails on generatePreview step

### ISSUE THREAD

**Issue by brennaveen** [OnsenUI/OnsenUI#2655]
__Environment__

Onsen UI Version:
2.10.8 

__Encountered problem__
Theme customization build fails on generatePreview step.

```shell
PS C:\git\myProject\node_modules\onsenui\css-components-src> yarn run serve
yarn run v1.16.0
$ gulp serve
[15:20:52] Using gulpfile C:\git\myProject\node_modules\onsenui\css-components-src\gulpfile.js
[15:20:52] Starting 'serve'...
[15:20:52] Starting 'build'...
[15:20:52] Starting 'build-css'...
[15:20:52] Starting 'cssClean'...
[15:20:52] Finished 'cssClean' after 50 ms
[15:20:52] Starting 'stylelint'...
[15:20:53] Finished 'stylelint' after 497 ms
[15:20:53] Starting 'cssnext'...
Node#before is deprecated. Use Node#raws.before
You are using @apply rule and custom property sets. 
This feature won't be included in next the major release of postcss-cssnext. 
This most likely won't get any more support from browser vendors as the spec is yet considered deprecated and alternative solutions are being discussed. 
Read more about the reason here https://github.com/pascalduez/postcss-apply.
[15:20:58] Finished 'cssnext' after 5.66 s
[15:20:58] Starting 'cssmin'...
[15:21:02] Finished 'cssmin' after 3.42 s
[15:21:02] Finished 'build-css' after 9.64 s
[15:21:02] Starting 'generatePreview'...
[15:21:02] 'generatePreview' errored after 5.54 ms
[15:21:02] Error: ENOENT: no such file or directory, open 'C:\git\myProject\node_modules\onsenui\css-components-src/build/onsen-css-components.css'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at parseComponents (C:\git\myProject\node_modules\onsenui\css-components-src\gulpfile.js:159:18)
    at generatePreview (C:\git\myProject\node_modules\onsenui\css-components-src\gulpfile.js:116:22)
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at asyncRunner (C:\git\myProject\node_modules\onsenui\css-components-src\node_modules\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[15:21:02] 'build' errored after 9.66 s
[15:21:02] 'serve' errored after 9.67 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

__How to reproduce__
- `npm install onsenui`
- `cd node_modules/onsenui/css-components-src`
- `yarn install --pure-lockfile
- `yarn run serve` or `npm run serve`

**Comment by Ftrybe** [comment]
Uncomment In the 95 line and 68 line.

**Comment by maurovanetti** [comment]
Same error, Ftrybe's fix nailed it.

**Comment by korkis** [comment]
Or only works fine on macos

**Comment by Khangeldy** [comment]
Hi thanks for great work. I have also trouble with `yarn run serve` command. In cssnext task i got `Cannot read property 'browsers' of undefined` error. Then i manually added browserlist. Afterwards it fails on `serve` task. Showing `fsevents is not contructor`. 
Version of onsen-ui  = ^2.11.1.
Mac OS Catalina

**Comment by emccorson** [comment]
Should be fixed now. Run `npm install` from the root directory and then `npm run watch:previewer` and `npm run serve:previewer` in separate terminals.
