### ISSUE TITLE
npm run docs:react failed

### ISSUE THREAD

**Issue by yong-asial** [OnsenUI/OnsenUI#3018]
```
➜  OnsenUI git:(master) npm run docs:react

> onsenui-monorepo@1.0.0 docs:react
> npm run --prefix react-onsenui gen-docs


> react-onsenui@1.13.0 gen-docs
> node ./scripts/docgen.js

Generating docs, this may take a while: ..
Error generating docs!

/Users/asial/projects/onsenui/OnsenUI/react-onsenui/scripts/docgen.js:32
      throw error;
      ^

Error: Command failed: /Users/asial/projects/onsenui/OnsenUI/react-onsenui/scripts/../../node_modules/react-docgen/bin/react-docgen.js /Users/asial/projects/onsenui/OnsenUI/react-onsenui/src/components/Row.jsx > /Users/asial/projects/onsenui/OnsenUI/react-onsenui/scripts/../docs/Row.json
Error with path "/Users/asial/projects/onsenui/OnsenUI/react-onsenui/src/components/Row.jsx": Error: No suitable component definition found.
Error: No suitable component definition found.
    at parse (/Users/asial/projects/onsenui/OnsenUI/node_modules/react-docgen/dist/parse.js:74:9)
    at Object.defaultParse [as parse] (/Users/asial/projects/onsenui/OnsenUI/node_modules/react-docgen/dist/main.js:64:29)
    at parse (/Users/asial/projects/onsenui/OnsenUI/node_modules/react-docgen/bin/react-docgen.js:106:17)
    at /Users/asial/projects/onsenui/OnsenUI/node_modules/react-docgen/bin/react-docgen.js:210:32
    at FSReqCallback.oncomplete (node:fs:207:5)

    at ChildProcess.exithandler (node:child_process:400:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/Users/asial/projects/onsenui/OnsenUI/react-onsenui/scripts/../../node_modules/react-docgen/bin/react-docgen.js /Users/asial/projects/onsenui/OnsenUI/react-onsenui/src/components/Row.jsx > /Users/asial/projects/onsenui/OnsenUI/react-onsenui/scripts/../docs/Row.json'
}
```

**Comment by emccorson** [comment]
I'm not able to reproduce this locally.
I did a fresh install and then:
```
npm install
npm run docs:react
```
but I'm not seeing an error.

Maybe it's a package version problem. Can you send me `npm ls`? It could maybe be the `react-docgen` version.

**Comment by yong-asial** [comment]
@emccorson 

Here is the installed version for react-docgen

```
➜  OnsenUI git:(master) ✗ npm ls | grep react-docgen
│ ├── react-docgen@5.4.2
```

and here is the `npm ls` result
[npm_ls.log](https://github.com/OnsenUI/OnsenUI/files/9623275/npm_ls.log)
