### ISSUE TITLE
Angular2 | Tabbar issue when using ons-tab

### ISSUE THREAD

**Issue by nchetbani** [OnsenUI/OnsenUI#3038]
__Environment__

  
```
[Core]
  onsenui latest : **onsenui 2.11.2**
  
[Framework]
  angular2 : **13.3.11**

[Framework binding]
 angular2-onsenui latest : **ngx-onsenui 7.0.0**

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 107.0.0.0 on Windows 10 64-bit
```

__Encountered problem__
  In my application, I use ons -tab like this:

- __HTML__

```html
<ons-page>
  <ons-toolbar>
    <div class="center">test</div>
    <div class="right">
      <ons-toolbar-button (click)="toggleMenu()">
        <ons-icon icon="md-menu"></ons-icon>
      </ons-toolbar-button>
    </div>
</ons-toolbar>
<div class="content">
    <ons-bottom-toolbar>
        <ons-tabbar>
            <div class="tabbar__content"></div>
            <div class="tabbar">
              <ons-tab label="Page1" icon="ion-ios-home" active-icon="ion-ios-home" [page]="tab1" active></ons-tab>
              <ons-tab label="Page2" icon="ion-ios-browsers" active-icon="ion-ios-home" [page]="tab2"></ons-tab>
              <ons-tab label="Page3" icon="ion-ios-search" active-icon="ion-ios-home" [page]="tab3"></ons-tab>
            </div>
        </ons-tabbar>
    </ons-bottom-toolbar>
</div>

</ons-page>
```
- __JS__
```typescript
import { Component } from '@angular/core';

import { MenuService } from '../menu.service';
import { Tab1Component } from './tab1/tab1.component';
import { Tab2Component } from './tab2/tab2.component';
import { Tab3Component } from './tab3/tab3.component';

@Component({
  selector: 'ons-page[page2]',
  templateUrl: './page2.component.html',
  styleUrls: [ './page2.component.scss' ]
})
export class Page2Component {
  tab1 = Tab1Component;
  tab2 = Tab2Component;
  tab3 = Tab3Component;

  constructor(private menuService: MenuService) { }

  toggleMenu() {
    this.menuService.toggle();
  }
}

@Component({
  selector: 'ons-page',
  template: `
  <p>tab1 works!</p>
`
})

export class Tab1Component {
  constructor() {
  }
}


@Component({
  selector: 'ons-page',
  template: `
  <p>tab2 works!</p>
`
})

class Tab2Component {
  constructor() {
  }
}

@Component({
  selector: 'ons-page',
  template: `
  <p>tab3 works!</p>
`
})

class Tab3Component {
  constructor() {
  }
}
```
but when loading the application I have this error: 
`       
 Uncaught TypeError: p._show is not a function
    at main.js:1:542803
    at main.js:1:289046
    at w (main.js:1:289157)
    at oe (main.js:1:288149)
    at q.invokeTask (polyfills.js:1:128670)
    at q.runTask (polyfills.js:1:123664)
    at q.invokeTask [as invoke] (polyfills.js:1:129819)
    at J (polyfills.js:1:143654)
    at se (polyfills.js:1:144060)
    at ce (polyfills.js:1:144264)
`
And when i try to click on the tabs I get this error:

`
Unhandled Promise rejection: v.pageElement._hide is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: v.pageElement._hide is not a function
    at HTMLElement.value (main.js:1:538438)
    at f.value (main.js:1:382405)
    at f.value (main.js:1:378994)
    at main.js:1:541661
    at q.invoke (polyfills.js:1:127981)
    at q.run (polyfills.js:1:122975)
    at polyfills.js:1:139006
    at q.invokeTask (polyfills.js:1:128670)
    at q.runTask (polyfills.js:1:123664)
    at he (polyfills.js:1:131098) TypeError: v.pageElement._hide is not a function
    at HTMLElement.value (http://localhost:4280/main.js:1:538438)
    at f.value (http://localhost:4280/main.js:1:382405)
    at f.value (http://localhost:4280/main.js:1:378994)
    at http://localhost:4280/main.js:1:541661
    at q.invoke (http://localhost:4280/polyfills.js:1:127981)
    at q.run (http://localhost:4280/polyfills.js:1:122975)
    at http://localhost:4280/polyfills.js:1:139006
    at q.invokeTask (http://localhost:4280/polyfills.js:1:128670)
    at q.runTask (http://localhost:4280/polyfills.js:1:123664)
    at he (http://localhost:4280/polyfills.js:1:131098)`

**Comment by yong-asial** [comment]
@nchetbani It seems that you are using Angular 8. Angular-onsenui only support [Angular 7](https://github.com/OnsenUI/OnsenUI/blob/master/ngx-onsenui/package.json#L17)  at the moment. 

If you need working example, you can check out this repo - https://github.com/monaca-templates/onsenui-v2-angular2-tabbar
