### ISSUE TITLE
Error installing vue-onsenui via npm 

### ISSUE THREAD

**Issue by r0gueSch0lar** [OnsenUI/OnsenUI#3069]
__Environment__

Onsen UI Version:

-  vue-onsenui@2.7.2

Framework:

- vue@"^3.3.4

Framework binding:

- 

Additional libraries:

- 

Platform:

- M1 MBP MacOS Ventura 13.5

__Encountered problem__

Getting error on install, have replicated the same error on a surface go 3 running Manjaro, onsenui by itself installs fine, vue-onsenui  seems to be the culprit. 

--- debug-0.log ---

0 verbose cli /opt/homebrew/Cellar/node/20.6.1/bin/node /opt/homebrew/bin/npm
1 info using npm@9.8.1
2 info using node@v20.6.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/********/Projects/Dev/VueJS-Boilerplate/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/********/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 4ms
17 timing npm:load:configload Completed in 4ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install onsenui vue-onsenui
22 verbose argv "install" "onsenui" "vue-onsenui" "--save"
23 timing npm:load:setTitle Completed in 3ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/Users/********/.npm/_logs/2023-09-19T03_59_52_682Z-
26 verbose logfile /Users/********/.npm/_logs/2023-09-19T03_59_52_682Z-debug-0.log
27 timing npm:load:logFile Completed in 4ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 19ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 1 files
33 timing idealTree:init Completed in 50ms
34 timing idealTree:userRequests Completed in 1ms
35 silly idealTree buildDeps
36 silly fetch manifest onsenui@*
37 silly logfile done cleaning log files
38 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
39 http fetch GET 200 https://registry.npmjs.org/onsenui 9ms (cache hit)
40 silly fetch manifest vue-onsenui@*
41 http fetch GET 200 https://registry.npmjs.org/vue-onsenui 42ms (cache hit)
42 silly fetch manifest vue@^3.3.4
43 http fetch GET 200 https://registry.npmjs.org/vue 3ms (cache hit)
44 silly fetch manifest vue@~2.6.0
45 timing idealTree Completed in 116ms
46 timing command:install Completed in 121ms
47 verbose stack Error: unable to resolve dependency tree
47 verbose stack     at #failPeerConflict (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1376:25)
47 verbose stack     at #loadPeerSet (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1342:33)
47 verbose stack     at async #buildDepStep (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:11)
47 verbose stack     at async Arborist.buildIdealTree (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
47 verbose stack     at async Promise.all (index 1)
47 verbose stack     at async Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
47 verbose stack     at async Install.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/install.js:149:5)
47 verbose stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli-entry.js:61:5)
48 verbose cwd /Users/********/Projects/Dev/VueJS-Boilerplate
49 verbose Darwin 22.6.0
50 verbose node v20.6.1
51 verbose npm  v9.8.1
52 error code ERESOLVE
53 error ERESOLVE unable to resolve dependency tree
54 error
55 error While resolving: vue-boilerplate@0.0.0
55 error Found: vue@3.3.4
55 error node_modules/vue
55 error   vue@"^3.3.4" from the root project
55 error
55 error Could not resolve dependency:
55 error peer vue@"~2.6.0" from vue-onsenui@2.7.2
55 error node_modules/vue-onsenui
55 error   vue-onsenui@"*" from the root project
55 error
55 error Fix the upstream dependency conflict, or retry
55 error this command with --force or --legacy-peer-deps
55 error to accept an incorrect (and potentially broken) dependency resolution.
56 error
56 error
56 error For a full report see:
56 error /Users/********/.npm/_logs/2023-09-19T03_59_52_682Z-eresolve-report.txt
57 verbose exit 1
58 timing npm Completed in 233ms
59 verbose unfinished npm timer reify 1695095992793
60 verbose unfinished npm timer reify:loadTrees 1695095992795
61 verbose unfinished npm timer idealTree:buildDeps 1695095992846
62 verbose unfinished npm timer idealTree:#root 1695095992846
63 verbose code 1
64 error A complete log of this run can be found in: /Users/********/.npm/_logs/2023-09-19T03_59_52_682Z-debug-0.log

__How to reproduce__

npm install onsenui vue-onsenui --save

**Comment by r0gueSch0lar** [comment]
just updating this installs fine via yarn
