### ISSUE TITLE
Javascript error using ons-pull-hook and ons-tabbar

### ISSUE THREAD

**Issue by EverlastingFire** [OnsenUI/OnsenUI#467]
Hi, I'm testing the new ons-pull-hook feature and I got a javascript error while switching tabs on ons-tabbar.

Look at the following code, which reproduce the issue: 
http://codepen.io/anon/pen/EaRzrG

It's just the ons-pull-hook demo with a ons-tabbar added.
Every time you switch tab, the following javascript error shows:
```
TypeError: undefined is not a function
    at Class.module.factory.Class.extend._destroyEventListeners (https://rawgit.com/OnsenUI/OnsenUI/master/build/js/onsenui.min.js:6:24454)
    at Class.module.factory.Class.extend._destroy (https://rawgit.com/OnsenUI/OnsenUI/master/build/js/onsenui.min.js:6:24515)
    at h.$get.h.$broadcast (https://rawgit.com/OnsenUI/OnsenUI/master/build/js/angular/angular.min.js:125:486)
    at h.$get.h.$destroy (https://rawgit.com/OnsenUI/OnsenUI/master/build/js/angular/angular.min.js:121:478)
    at https://rawgit.com/OnsenUI/OnsenUI/master/build/js/onsenui.min.js:7:26973
    at Class.TabbarAnimator.extend.apply (https://rawgit.com/OnsenUI/OnsenUI/master/build/js/onsenui.min.js:7:22355)
    at Class.extend.prototype.(anonymous function) [as apply] (https://rawgit.com/OnsenUI/OnsenUI/master/build/js/onsenui.min.js:2:2075)
    at Class.extend._switchPage (https://rawgit.com/OnsenUI/OnsenUI/master/build/js/onsenui.min.js:7:26872)
    at Class.extend._loadPageDOM (https://rawgit.com/OnsenUI/OnsenUI/master/build/js/onsenui.min.js:7:27426)
    at Class.<anonymous> (https://rawgit.com/OnsenUI/OnsenUI/master/build/js/onsenui.min.js:7:26520)
```

Removing the ons-pull-hook element from the starting tab makes the error disappear, e.g. if I remove it from test1.html and then I go from test1.html to test2.html everything is fine.

**Comment by argelius** [comment]
Thanks @EverlastingFire , I'll check it out!

**Comment by argelius** [comment]
@EverlastingFire 

The issue has been fixed now. Thanks for including the failing example as well. It's very helpful.

It will be fixed in the next release but if you want to use it straight away you can build from source or download the latest build here:
http://onsen.io/download.html#latest-build
