### ISSUE TITLE
issue when jQuery plugin initalize as directive

### ISSUE THREAD

**Issue by kalevieino** [OnsenUI/OnsenUI#528]
Dear OnsenUI team

In ons-page Controller I was trying to create a directive (Attribute) then add jQuery plugin (mobiscroll time inline), but exceptions occur.
- Directive Definition
```js
  (function() {
  'use strict';
  
  var module = angular.module('scaDirectives', []);
  
  module.directive('mobiDatetimeInline', function() {
    return {
      restrict: 'A',
      link: function(scope, elem, attrs) {
        angular.element(elem[0]).mobiscroll().time({
          mode: 'scroller',
          display: 'inline',
          height: 30
        });
      }
    };
  });
  })();
```
- element
```html
  <input type="text" class="mobi_time"  mobi-datetime-inline />
```
- exception
```
  TypeError: Cannot read property 'nodeName' of undefined
  at Object.fireComponentEvent (http://localhost:8901/lib/onsen/js/onsenui.js:20210:30)
  at module.directive.link (http://localhost:8901/lib/onsen/js/onsenui.js:15392:16)
  at invokeLinkFn (http://localhost:8901/lib/angular/angular.js:8258:9)
  at nodeLinkFn (http://localhost:8901/lib/angular/angular.js:7768:11)
  at compositeLinkFn (http://localhost:8901/lib/angular/angular.js:7117:13)
  at nodeLinkFn (http://localhost:8901/lib/angular/angular.js:7763:24)
  at compositeLinkFn (http://localhost:8901/lib/angular/angular.js:7117:13)
  at compositeLinkFn (http://localhost:8901/lib/angular/angular.js:7120:13)
  at compositeLinkFn (http://localhost:8901/lib/angular/angular.js:7120:13)
  at nodeLinkFn (http://localhost:8901/lib/angular/angular.js:7763:24) angular.js:11655 (anonymous function)angular.js:8596 $getangular.js:8260 invokeLinkFnangular.js:7768 nodeLinkFnangular.js:7117 compositeLinkFnangular.js:7763 nodeLinkFnangular.js:7117 compositeLinkFnangular.js:7120 compositeLinkFnangular.js:7120 compositeLinkFnangular.js:7763 nodeLinkFnangular.js:7117 compositeLinkFnangular.js:6996 publicLinkFnonsenui.js:9194 module.factory.Class.extend._createPageElementAndLinkFunction.linkonsenui.js:9441 module.factory.Class.extend._pushPageDOMonsenui.js:9320 (anonymous function)onsenui.js:4494 (anonymous function)onsenui.js:4513 runIfPresentonsenui.js:4559 onGlobalMessage
```

I am not sure what I mistook so please help me kindly.

Regards,
Kalevi

**Comment by kalevieino** [comment]
I referenced http://stackoverflow.com/questions/16935095/correct-way-to-integrate-jquery-plugins-in-angular-js

**Comment by argelius** [comment]
Hi @kalevieino !

We'll take a look at this. Thanks!
