### ISSUE TITLE
$compileProvider.debugInfoEnabled

### ISSUE THREAD

**Issue by tunacoder** [OnsenUI/OnsenUI#845]
Hi Onsen team

I use OnsenUI with Angular.js. 

When I do $compileProvider.debugInfoEnabled(false), ons.notification.confirm() occurs an exception.

Here are code:
  module.config(['$compileProvider', function($compileProvider) {
    $compileProvider.debugInfoEnabled(false);
  }]);

Exception location:
Error: AngularJS Scope is null. Argument DOM element must be attached in DOM document.
    at Object.window.ons.ons.compile (http://localhost:8901/lib/onsen/js/onsenui.min.js:4:14894)
    at window.ons.notification.createAlertDialog (http://localhost:8901/lib/onsen/js/onsenui.min.js:10:2771)
    at Object.window.ons.notification.confirm (http://localhost:8901/lib/onsen/js/onsenui.min.js:10:4535)
    at n.$scope.logout (http://localhost:8901/js/app.js:142:24)
    at fn (eval at <anonymous> (http://localhost:8901/lib/angular/angular.min.js:212:83), <anonymous>:4:209)
    at http://localhost:8901/lib/onsen/js/onsenui.min.js:9:15251
    at n.$get.n.$eval (http://localhost:8901/lib/angular/angular.min.js:134:493)
    at n.$get.n.$apply (http://localhost:8901/lib/angular/angular.min.js:135:217)
    at HTMLElement.click dblclick mousedown mouseup mouseover mouseout mousemove mouseenter mouseleave keydown keyup keypress submit focus blur copy cut paste.split.forEach.ngEventDirectives.(anonymous function).compile.listener (http://localhost:8901/lib/onsen/js/onsenui.min.js:9:15233)
    at HTMLElement.c (http://localhost:8901/lib/angular/angular.min.js:35:217)

Please take care of that issue.

**Comment by argelius** [comment]
Thanks @tunacoder ! We will investigate this issue.

**Comment by argelius** [comment]
@tunacoder: I've released a new version where the `ons.notification.*` functions work even if debug info is disabled.

Please try it out. I will close this but if you're still having issues please open this again.

**Comment by komachi** [comment]
I experience the same issue with 2.0.0-rc.7 and angular 1.5.6. Enabling debugInfo back makes it work. I created a codepen to demonstrate the issue http://codepen.io/komachi/pen/KMwvEV

**Comment by IliaSky** [comment]
It seems that in `ons.compile` we are trying to use `angular.element(...).scope()`, which returns `undefined` while `debugInfo` is disabled. 

I looked though most commits between Sep 4-7, but wasn't actually able to find the fix. It was added to the changelog, but maybe the fix itself was in another place and might have been overridden, I'm not sure. As it stands now it looks like the issue still persists. 

Some libraries seem to be overriding `$$addScopeInfo` themselves, basically enabling the `scope()` even when debugging is disabled. I'm not really sure how it was solved in our case last time.

**Comment by IliaSky** [comment]
@komachi - I guess the fix was lost somewhere along the way. It has just been reapplied, so it will be available in rc.8.

**Comment by komachi** [comment]
@IliaSky Great, thanks!

**Comment by d3orn** [comment]
disabling debug in Onsen 1.3.17 still throws this error
